### ISSUE TITLE
不能直接ctrl+V复制图片

### ISSUE THREAD

**Issue by AvaterXXX** [sec-report/SecReport#11]
编写报告不能直接Ctrl+V复制图片，只能上传

**Comment by sec-report** [comment]
请提供浏览器版本以及Ctrl+C来源

**Comment by AvaterXXX** [comment]
浏览器用的火狐最新版 ctrl+c就是截图工具截图的 不限于微信、qq等，下载了最新版本1.0.6也不行，只能上传图片

**Comment by AvaterXXX** [comment]
![image](https://github.com/sec-report/SecReport/assets/30459279/853ce6f9-33bb-4a5a-8d95-6058f8b69d59)
报错这个

**Comment by sec-report** [comment]
看起来像是老版本的Bug，docker可能存在该问题，官网应该是没问题的

**Comment by AvaterXXX** [comment]
部署本地没看到新版本，官网的版本什么时候同步到docker？

**Comment by sec-report** [comment]
> 部署本地没看到新版本，请问师傅，官网的版本什么时候同步到docker……

今晚或明天更新
