### ISSUE TITLE
报告存在乱码

### ISSUE THREAD

**Issue by GnibUhs** [sec-report/SecReport#12]
添加测试过程，输出报告存在乱码，以及图片大小未适应
![60ece96b58746339c9b091fb3c4e521](https://github.com/sec-report/SecReport/assets/113746869/0bca9457-6a74-4040-8aa5-7a9c3d440210)

**Comment by sec-report** [comment]
请提供word版本

**Comment by sec-report** [comment]
#7

**Comment by GnibUhs** [comment]
使用的是默认模板

**Comment by sec-report** [comment]
是官网版本吗？私有化部署docker暂未解决 #7 问题

**Comment by aiilq** [comment]
应该如何使用
![Uploading Snipaste_2024-06-05_16-09-54.jpg…]()

**Comment by sec-report** [comment]
> 应该如何使用，提示初始化TOTP令牌

https://support.microsoft.com/zh-cn/account-billing/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85microsoft-authenticator%E5%BA%94%E7%94%A8-351498fc-850a-45da-b7b6-27e523b8702a
可以尝试用这个
