### ISSUE TITLE
上传模板后无法输出报告

### ISSUE THREAD

**Issue by AvaterXXX** [sec-report/SecReport#13]
已经更新了最新版本，可正常复制图片了，但是上传模板后导出报告一直在转圈
![image](https://github.com/sec-report/SecReport/assets/30459279/7b6e57d9-e789-4e68-adfc-d9b2eb62b0e5)
使用的是template里面自带的docx，如果选择默认是可以导出的，自己新建一个
```
{{FOR t IN testBasis}}
{{$t}}
{{END-FOR t}}
```
也是可以导出的，是否是自带的模板语法出现了问题？能否增加报错机制或debug模式

**Comment by sec-report** [comment]
请下载最新demo，后续会增加模版报错机制。

**Comment by sec-report** [comment]
模版报错机制已增加
