### ISSUE TITLE
建议：漏洞列表添加漏洞地址模块

### ISSUE THREAD

**Issue by linfeng7z** [sec-report/SecReport#15]
建议在填写漏洞列表时添加一个漏洞地址模块，如果说一个系统多个路径下存在同一种类型的漏洞，不添加详细漏洞地址在导出报告后看起来很怪异
![image](https://github.com/sec-report/SecReport/assets/137154745/a497bb9b-d592-499d-8e86-ff7269683aa1)

**Comment by sec-report** [comment]
已更新，详见[v1.0.9](https://github.com/sec-report/SecReport/releases/tag/v1.0.9)
