### ISSUE TITLE
模板上传识别失败

### ISSUE THREAD

**Issue by qwer-sketch** [sec-report/SecReport#16]
上传模板之后识别不了模板

![1731317372066](https://github.com/user-attachments/assets/5c0911e4-d532-4ed5-b764-dca8e085fc82)
![1731317409244](https://github.com/user-attachments/assets/da894fdd-f588-4b42-9460-19169aa53d87)

**Comment by qwer-sketch** [comment]
I also have this problem, whether it's the official demo site or the one I built myself, they all failed to obtain it

**Comment by sec-report** [comment]
由于本次更新模版分为系统、团队和个人，mongodb在$in一个空团队的数组时会抛出异常。目前[v2.0.1](https://github.com/sec-report/SecReport/releases/tag/v2.0.1)已经修复该问题，请体验。
