### ISSUE TITLE
测试过程部分经常丢失

### ISSUE THREAD

**Issue by linfeng7z** [sec-report/SecReport#17]
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/a9b7bc87-bf2a-4668-82a7-e682ec400a1a">
测试过程频繁丢失，就是单个漏洞填写久一点以后再填写下一个漏洞，然后回过头来再看看刚才填写的漏洞情况，那个测试过程就消失了，有时候一定要重启才能出现，有时候重启以后又发现测试过程只保留了一部分

**Comment by sec-report** [comment]
一个更新依赖太激进导致的bug，已回退

**Comment by linfeng7z** [comment]
更新以后用过一段时间发现问题仍然存在，这个不知道跟docker、docker-compose或者系统版本有关吗
