### ISSUE TITLE
报告无法导出

### ISSUE THREAD

**Issue by Bluestar-coder** [sec-report/SecReport#3]
![image](https://user-images.githubusercontent.com/27113743/232259684-76c80012-74ed-4830-9053-2d2b0fed9865.png)
已经转了两天，报告依然无法导出

**Comment by sec-report** [comment]
已更新导出逻辑，刷新试试 (;

**Comment by Bluestar-coder** [comment]
![image](https://user-images.githubusercontent.com/27113743/232277738-bf50d8db-883a-4d72-87cd-703c4114700a.png)
在新创中尝试编写了一个漏洞信息，仍无法导出。
![image](https://user-images.githubusercontent.com/27113743/232277885-69c293ea-5509-4915-b0dc-491a4300d823.png)


如果无漏洞信息，导出很顺畅。
![image](https://user-images.githubusercontent.com/27113743/232277937-eb0fcccd-84f7-4b15-8ca8-92016762af3f.png)

**Comment by Bluestar-coder** [comment]
同时 能否提供一个word模板Demo ？

**Comment by sec-report** [comment]
经过排查，定位到是S3存储的问题，已经修复。另外添加了即使图片加载失败，文档依然可以导出的逻辑，欢迎试用。word模版 demo在计划之中，计划于下周提供。
