### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by GokmanPang** [sec-report/SecReport#7]
![image](https://github.com/sec-report/SecReport/assets/59789973/5d70a1f0-2776-4482-a792-de73dbd64519)

**Comment by sec-report** [comment]
office什么版本。升级office试试

**Comment by GokmanPang** [comment]
> office什么版本。升级office试试

LTSC专业增强版2021，是office问题，用WPS可以没问题。

**Comment by sec-report** [comment]
虽然我没有使用2021复现，但是我在代码中强制了 UTF-8 编码，可以再试试

**Comment by GokmanPang** [comment]
> 虽然我没有使用2021复现，但是我在代码中强制了 UTF-8 编码，可以再试试

已解决，2021可正常显示

**Comment by sec-report** [comment]
> > 虽然我没有使用2021复现，但是我在代码中强制了 UTF-8 编码，可以再试试
> 
> 已解决，2021可正常显示

感谢测试
