### ISSUE TITLE
单机版镜像会进行升级吗

### ISSUE THREAD

**Issue by Lidong-io** [sec-report/SecReport#9]
师傅你好，报告生成平台非常好用，发现docker还停留在三个月前，没有图片粘贴的功能，请问docker会同步升级吗
![图片](https://github.com/sec-report/SecReport/assets/59634396/f11321bb-728d-4f0a-9843-70de863308b5)

**Comment by sec-report** [comment]
在计划之中

**Comment by zzj990510** [comment]
计划什么时候
